//Expressões Comparativas
		// <expressão> = <valor verdade>
		// Operadores Comparativos:
		// > = maior >= maior ou igual
		// < = menor <= menor ou igual
		// == igual != diferente
int x  = 5;
X > 0 // Resultado: V
X == 3 // Resultado: F
10 <= 30 //Resultado: V
X != 2 // Resultado: V


//Expressões lógicas
		// <expressão> = <valor verdade>
		// Operadores lógicos:
		// && = e <todas condições devem ser verdadeiras>
		// || = ou <pelo menos uma condição deve ser verdadeira>
		// ! = não <inverte a condição>
    
X <= 20 && X == 10 //Resultado: V
X > 0 && X != 3  //Resultado: V
X <= 20 && X == 10 && X != 3 //Resultado: F
